### ISSUE TITLE
Villager ImageUri error on id:1

### ISSUE THREAD

**Issue by raknam** [alexislours/ACNHAPI#11]
https://github.com/alexislours/ACNHAPI/blob/master/v1a/villagers.json#L28 should be `https://acnhapi.com/v1/images/villagers/1`

**Comment by alexislours** [comment]
Fixed on [c7s2003](https://github.com/alexislours/ACNHAPI/commit/c7d20037fe3d5002e073c6f7f957d319a0fc9083), thanks for bringing it up!
