### ISSUE TITLE
Inconsistency with fish shadow sizes

### ISSUE THREAD

**Issue by rabross** [alexislours/ACNHAPI#18]
There seems to be an inconsistency with fish shadow sizes.
I'm assuming there are 6 size differences but `"Medium (4)"` and `"Large (4)"` appear in the list.

Example
[Soft shelled turtle](https://acnhapi.com/v1/fish/12) is `"Medium (4)"`
[Koi](https://acnhapi.com/v1/fish/6) is `"Large (4)"`

Is there a difference?

**Comment by alexislours** [comment]
Hi, yes, the Koi value is incorrect in this case. This part of the data was done by hand before most data was datamined, I'll correct it on next push. Thanks for reporting.

**Comment by alexislours** [comment]
Corrected in 520124f17b98bfb6adf95eba8d2173bbcdc48010 .
