### ISSUE TITLE
Question: Do you have any reference to a list of items required for a craftable item

### ISSUE THREAD

**Issue by CephNightmare** [alexislours/ACNHAPI#22]
Hi,

I've been working with this API with great pleasure, and have another question. I noticed that there isn't an 'ingredient list' for craftable items. Do you know of any way to include this? Or do you perhaps have another resource i could utilize to fetch that data?

Kind Regards!

**Comment by alexislours** [comment]
Hi, I don't plan to include this (at least yet) as I wouldn't have time to maintain it without it being half baked. You can find more information here if you wish. https://tinyurl.com/acnh-sheet

**Comment by CephNightmare** [comment]
Thanks for the sheet, that's indeed very helpful!

**Comment by igromanru** [comment]
If the google sheet most up to date, make a script that parses it each night and updates you API with it.
Just an idea.

**Comment by alexislours** [comment]
This is currently something that i'm working on. I'm also working with the people involved in this sheet every updates and bunch of other stuff. You only have so much time available.
