### ISSUE TITLE
Use more standard language tags for item names

### ISSUE THREAD

**Issue by neverwhelm** [alexislours/ACNHAPI#25]
Currently, names use what seem to be a propietary standard (name-EUen, name-USen, etc.).

It'd be worth considering changing them into a more standard format, for example: 'name-en-US' or 'name-en-GB'.

This would make it easier to work with most language libraries that conform with [BCP47](https://www.ietf.org/rfc/bcp/bcp47.txt). In HTML, a non-conforming attribute results in 'invalid' being used instead.

Of course, this can be solved on an app level but it'd be ideal if we could get it directly from the API.

This change will be breaking unless we maintain both versions of the language tag.

**Comment by alexislours** [comment]
See https://github.com/alexislours/ACNHAPI/issues/5 . 
Language codes respect the ones in the game and aren't specific to countries and don't follow any ISO and forcing an ISO on them would be wrong. EUen would also apply to Australia and EUfr would also be used for a French Belgian. 

I have a more in depth explanation on my translation sheet here if you want to have a full explenation on what X country code means. https://docs.google.com/spreadsheets/d/1GwUuCKgJC61qWEjWyeG3nVjkHesszRL6XbPA_dHfLoI/edit#gid=1761059337

**Comment by neverwhelm** [comment]
My bad, I should have checked previous issues!

I still think it'd be worth looking into maybe as additional piece of data in the object (rather than replace the current way). I'd be willing to work on this, but of course if it isn't something you're interested in seeing in the API right now, feel free to close the issue.
