### ISSUE TITLE
image_uri for some fossils don't work

### ISSUE THREAD

**Issue by sydeslyde** [alexislours/ACNHAPI#26]
There are some fossils of which the `image_uri` does not work.

To be specific:
- https://acnhapi.com/v1/fossils/pachy_skull -> https://acnhapi.com/v1/images/fossils/plesio_torso
- https://acnhapi.com/v1/fossils/pachy_tail -> https://acnhapi.com/v1/images/fossils/pachy_tail
- https://acnhapi.com/v1/fossils/pachy_skull -> https://acnhapi.com/v1/images/fossils/pachy_skull

**Comment by alexislours** [comment]
Should be corrected on the server side, thanks for pointing it out!
