### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by Lunnatica** [alexislours/ACNHAPI#30]
Hi! 

The API is not working for HTTPS because the certificate on the page has expired (see screenshot).

<img width="744" alt="Screenshot 2021-05-25 at 22 00 32" src="https://user-images.githubusercontent.com/4697967/119567901-cad25400-bda4-11eb-947c-62aefe4f473a.png">

**Comment by alexislours** [comment]
renewed

**Comment by Lunnatica** [comment]
Thank you for the quick fix! 🚀
