### ISSUE TITLE
JSON Elements as List?

### ISSUE THREAD

**Issue by alexandertheis** [alexislours/ACNHAPI#4]
Hello,

is it possible to get for example bugs or fish as a list in JSON file? I think it would be much easier to parse the JSON response.

Greets
Alex

**Comment by alexislours** [comment]
Hi,

You can easily parse the response with a "for in" loop if you're doing JS. I might add an endpoint later on that returns a JSON array but too many tools are based on the current format for me to change it right away.

**Comment by alexandertheis** [comment]
Thank you much for the fast answer. I will try it with a for loop. I will watch the project for new endpoints in future. Thanks for that your great work!
