### ISSUE TITLE
Names property as country code

### ISSUE THREAD

**Issue by igromanru** [alexislours/ACNHAPI#5]
Isn't it better to use ISO 3166 country codes for name properties?  
I'm using an earlier revision and villagers Spanish name were "name-es" there. I found it better this way, because it's official ISO 3166 country code for Spain.  
https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by alexislours** [comment]
Hi, 
The language codes won't be updated for now as quite a few apps are based on them. If I were to update them, they would follow the codes in the game files as they are more language code than country code, and be on a different endpoint.

These are the language codes inside the game files: 

- CNzh (Simplified Chinese
- EUde (German)
- EUen (English non US)
- EUes (Spanish)
- EUfr (French)
- EUit (Italian)
- EUru (Russian)
- JPja (Japanese)
- KRko (Korean)
- TWzh (Traditional Chinese)
- USen (English US)
- USes (Latin American Spanish)
- USfr (Canadian French)

These are determined based on the language and region of the console, not the country.

**Comment by igromanru** [comment]
Thank for your reply.  
I see, it's better to name it like in game.   
But is it really a problem to change it to es or enes, I guess Apps should use a special revision anyway and it's not hard to update.

**Comment by alexislours** [comment]
Yes, it wouldn't be hard to update but it would still require an update. And with 300 000+ calls today, I'd prefer doing that on a separate endpoint at first. But it will definitely be this way in the future. :)
