### ISSUE TITLE
Map the images/icons to the item

### ISSUE THREAD

**Issue by CoryWritesCode** [alexislours/ACNHAPI#7]
Is there a reason why the images/icons aren't mapped to the item/village/fish/etc... so two api calls wouldn't be necessary?

Just curious!

**Comment by alexislours** [comment]
Hi,
The main reason the images/icons are separated is to make it clear for beginners. I know a lot of users are actually pretty new at this. Embedding the images in B64 within the response would both slow down the loading a lot for users and include useless data for people who only want the image/icon or the JSON response. Making a multipart response would also make it harder for these people. I'm nowhere near reaching a bottleneck on my end so I feel like this is the appropriate solution. 

The API is also still under development, so such changes might come on the long run.

There is also the fact that a lot of app are already built on it this way which make drastic changes harder to implement (which is something I hadn't planned when I first created this).

**Comment by CoryWritesCode** [comment]
I understand. I think my only issue is if one were making a list of villagers (which is easy to list via the `/villagers/` endpoint, if someone wanted the icons of the villagers along with the name of the villager then it makes it more complex to then make a seperate call for each villager icon.

I understand the development/level of coding ability point as well. Just a thought

**Comment by CoryWritesCode** [comment]
Maybe even adding the `name` prop instead of just file_name or id might be helpful too.

**Comment by alexislours** [comment]
Sure, I'll add the English name for the villager endpoint in the coming days now that I reworked the back-end. Adding more languages wouldn't really be possible as some different villagers share the same name but in different languages.

**Comment by CoryWritesCode** [comment]
Totally get that.
Second "enhancement" thought on this actually. Too keep the data steam low, and not break previous implementations maybe you could add an `imageUri`/`iconUri` to the item endpoints. (I can do this for you if you want! Since it would be kind of tedious). That way it's not importing the image bits but rather at least a quicker reference to the api call. So if say, I wanted to pull the villager with `id: 24` the response might look like this

```json
{
    "id": 24,
    "file-name": "brd01",
    "name": {
        "name-en": "Robin",
        "name-eneu": "Robin",
        "name-de": "Jule",
        "name-sp": "Aria",
        "name-spus": "Aria",
        "name-fr": "Robie",
        "name-frus": "Robie",
        "name-it": "Rossana",
        "name-nl": "Robin",
        "name-cn": "喳喳",
        "name-tw": "喳喳",
        "name-jp": "パーチク",
        "name-kr": "파틱",
        "name-ru": "Робин"
    },
    "personality": "Snooty",
    "birthday-string": "December 4th",
    "birthday": "4/12",
    "species": "Bird",
    "gender": "Female",
    "catch-phrase": "la-di-da",
    "image_uri": "https://acnhapi.com/images/villagers/24",
    "icon_uri": "https://acnhapi.com/icons/villagers/24"
}
```

and I can add the image_uri to the image component in my code and it would just fetch it when mounting.

**Comment by alexislours** [comment]
I'll do that on Tuesday, thanks for the feedback.

**Comment by CoryWritesCode** [comment]
I actually already did haha. wrote a small script to do the heavy lifting. Mind if I make a PR?

**Comment by alexislours** [comment]
Fixed and uri keys added to all endpoints, will update the doc.
